<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Pic</AssemblyName>
    <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pic.Capture\Pic.Capture.csproj" />
    <ProjectReference Include="..\Pic.Recorder\Pic.Recorder.csproj" />
    <ProjectReference Include="..\Pic.Editor\Pic.Editor.csproj" />
    <ProjectReference Include="..\Pic.Shared\Pic.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

</Project>
